### ISSUE TITLE
InexactError() in the examples

### ISSUE THREAD

**Issue by CarloLucibello** [zyedidia/Chipmunk.jl#2] opened 2015-09-11 08:32 UTC
I hit the same error in pyramid_topple.jl, shapes.jl  and simple.jl.

```
[carlo@x1 examples]$ julia pyramid_topple.jl 
/home/carlo/.julia/v0.4/SFML/deps
ERROR: LoadError: InexactError()
 in convert at bool.jl:6
while loading /home/carlo/.julia/v0.4/Chipmunk/examples/pyramid_topple.jl, in expression starting on line 65
```

My julia version is a two days old master.

Cheers

**Comment by zyedidia** [comment] 2015-09-12 17:24
I'm not sure what the problem is here... It's not happening for me. Does `Bool(1)` give you `true` in the shell?

**Comment by CarloLucibello** [comment] 2015-09-16 10:07
Il giorno sab 12 set 2015 alle ore 19:24 zyedidia notifications@github.com
ha scritto:

**Comment by zyedidia** [comment] 2015-09-16 22:39
Do the SFML examples work for you? It seems like the problem is that in the `SFML.isopen()` function, the ccall is not returning a 0 or 1 like it should, but some other number.

**Comment by CarloLucibello** [comment] 2015-09-17 09:19
Most SFML examples work, except for those where some resources have to be
loaded. This for a path related issue on linux. btw: I just changed my
gitHub name from Kalandin to CarloLucibello

Il giorno gio 17 set 2015 alle ore 00:39 zyedidia notifications@github.com
ha scritto:

**Comment by zyedidia** [comment] 2015-09-18 00:35
What is the path related issue?

**Comment by CarloLucibello** [comment] 2015-09-18 06:01
sorry, my bad, I was executing the SFML examples from the examples folder
and not from the, let's say, Audio subfolder. No problem there.

Il giorno ven 18 set 2015 alle ore 02:35 zyedidia notifications@github.com
ha scritto:

**Comment by opyate** [comment] 2015-09-25 06:09
I would like to report that I'm also seeing this issue, e.g. with [shapes.jl](https://github.com/zyedidia/Chipmunk.jl/blob/30d6e5767ecf0173d534cf34c17e59e0ab28cf28/examples/shapes.jl):

> ERROR: LoadError: InexactError()
>  in convert at bool.jl:6
>  in color_for_shape at /home/opyate/.julia/v0.5/Chipmunk/src/julia/cpDebugDraw.jl:88
>  in debug_draw at /home/opyate/.julia/v0.5/Chipmunk/src/julia/cpDebugDraw.jl:135
>  in main at /Chipmunk/examples/shapes.jl:63
>  in include at ./boot.jl:261
>  in include_from_node1 at ./loading.jl:304
>  in process_options at ./client.jl:275
>  in _start at ./client.jl:375
> while loading /Chipmunk/examples/shapes.jl, in expression starting on line 68

All the SFML examples work for me.

The error happens when it makes a [`ccall` into `libchipmunk`](https://github.com/zyedidia/Chipmunk.jl/blob/332667a90323c5dd78c63efb888908de3c6060ed/src/julia/cpDebugDraw.jl#L135)

**Comment by zyedidia** [comment] 2015-09-25 16:43
Both these errors are coming from a conversion from `Int32` to `Bool`. In your example, the error happens in the `color_for_shape` function on line 88, which is called as a callback from C on line 135. I'm not sure why `is_sleeping` in `libchipmunk` isn't returning an Int32 which is either 0 or 1. Could you possibly try printing the result of the ccall?

Change line 71 in `cpBody.jl` from

```
Bool(ccall(dlsym(libchipmunk, :cpBodyIsSleeping), Int32, (Ptr{Void},), body.ptr))
```

to 

```
println(ccall(dlsym(libchipmunk, :cpBodyIsSleeping), Int32, (Ptr{Void},), body.ptr))
return false
```

Please let me know what the output is.

Thanks!

**Comment by opyate** [comment] 2015-09-25 17:55
Here's the output (longer if I run it longer):

```
1992503808
1993237760
1993238016
1993238528
1993238784
1993239040
1993239552
1993239808
1993240064
1993240320
1993240832
1993241088
1993241344
1993241856
1993242112
1993242624
1993242880
1993243136
1993243392
1993243904
1993244160
1993867264
1993867776
1993868032
1993868288
<snip>
```

BTW, I tried with the latest version of Chipmunk2D by doing this:

Upgrade from cmake 2.8:

```
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install -y cmake
```

Get latest graphics dependencies:

```
sudo apt-get -y freeglut3-dev libglew-dev libglfw-dev
```

Clone fresh Chipmunk.jl, pin to v0.0.3, and change build.jl to copy `realpath("src/libchipmunk.so")` instead of `"src/libchipmunk.so.7.0.0"`, then `Pkg.build("Chipmunk")`.

It still failed, but returning false as you suggested ran the demo.

**Comment by zyedidia** [comment] 2015-09-25 19:19
It should be returning either 0 or 1. The C code for that function in Chipmunk is

```
return (body->sleeping.root != ((cpBody*)0));
```

I'm not sure how to help you any further. You could try adding a print statement in there, it's line 133 in `deps/Chipmunk2D/src/cpBody.c`. To rebuild just run `build.jl` again.

I would recommend just having the `is_sleeping` function return false.

**Comment by opyate** [comment] 2015-09-25 19:57
I changed line 71 in cpBody.jl from

```
Bool(ccall(dlsym(libchipmunk, :cpBodyIsSleeping), Int32, (Ptr{Void},), body.ptr))
```

to

```
Bool(ccall(dlsym(libchipmunk, :cpBodyIsSleeping), Uint8, (Ptr{Void},), body.ptr))
```

...and it now works.

`cpBool` is an `unsigned char` (source http://chipmunk-physics.net/release/ChipmunkLatest-API-Reference/group__basic_types.html#gabc5e752c48f3449ca26ef413ecbd647e) and in Julia `unsigned char` is a `Uint8` (source http://docs.julialang.org/en/release-0.3/manual/calling-c-and-fortran-code/?highlight=ccall#type-correspondences).

I don't have Mac or Windows, but do you think this fix will work on those platforms?
(I can test on a Mac next week Wednesday soonest, and have never really seen or used a Windows machine)

**Comment by zyedidia** [comment] 2015-09-25 21:35
That's great, thank you! This also works on Mac, and Windows isn't supported. I've added this fix in, but I'll refrain from closing this issue because I don't know if this also fixes the problem @CarloLucibello had.

**Comment by CarloLucibello** [comment] 2015-09-26 15:33
Nice, last commit fixes my problem as well. Thanks everybody

**Closed as completed** 2015-09-26 16:25 UTC
